track_parcel:
  fields:
    tracking_code:
      required: true
      example: "Z9998887776"
      selector:
        text:
    direction:
      default: incoming
      selector:
        select:
          options:
            - "incoming"
            - "outgoing"

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "Z9998887776"
      selector:
        text:
